# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20170706_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='students',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='school', to='school.Student'),
        ),
    ]
